### ISSUE TITLE
Shuffle bot doesn't play and clears queue on $m.play

### ISSUE THREAD

**Issue by eoanodea** [jbelford/ShuffleBot#6]
It looks like everything else is working fine, I can import a playlist from Spotify and add it to the queue, or add a song from youtube to the queue, but whenever I try $m.play, the bot will join the voice channel, but I can't hear anything. The queue is also cleared whenever I run that command.

I tested this in my own server, and your test server and got the same result.

**Comment by jbelford** [comment]
This was due to old version of ytdl no longer working. It's fixed now.
